media_entity.bundle.*.third_party.hide_revision_field:
  type: mapping
  label: 'Hide Revision Field'
  mapping:
    hide:
      type: boolean
      label: 'Whether to hide the revision field on this media type'
